#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LeftDrive,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightDrive,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Making a variable to measure the encoder speed
int MEN;
task main()
{

	//setting the encoders to 0
	nMotorEncoder[motorB] = 0;
	motor[RightDrive] = 50;

	while(true)
	{
		//asigning the variable MEN the motor encoder value
		MEN = nMotorEncoder[RightDrive];
		//asking if the motor power is greater than 0
		if(motor[RightDrive] > 15 || motor[RightDrive] < -15)
		{
			//asking whether the variable MEN (motor encoder number) is within 80 encoder ticks. of the encoder value
			if(nMotorEncoder[RightDrive] < MEN + 40 || nMotorEncoder[RightDrive] > MEN - 40)
			{
				//turning the motor off
				motor[RightDrive] = 0;
				//waiting for 3 seconds so we can debug easier
			}
			else
			{
				motor[RightDrive] = 50;
			}
		}
		//taking another reading, so if we use this, it will be able to repeat
		MEN = nMotorEncoder[RightDrive];
	}

}
