#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LeftDrive,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightDrive,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Making a variable to measure the encoder speed
int MEN;
task main()
{

	//setting the encoders to 0
	nMotorEncoder[RightDrive] = 0;
	motor[RightDrive] = 50;	//starts motors
	wait1Msec(1000);

	while(true)
	{
		//asigning the variable MEN the motor encoder value
		MEN = nMotorEncoder[RightDrive];
		//asking if the motor power is greater than 0
		if(motor[RightDrive] > 15 || motor[RightDrive] < -15)
		{
			wait1Msec(1000);
			//asking whether the variable MEN (motor encoder number) is within 80 encoder ticks. of the encoder value
			if(nMotorEncoder[RightDrive] < MEN + 100 || nMotorEncoder[RightDrive] > MEN - 100)//nME !=
			{
				//turning the motor off
				motor[RightDrive] = 0;
			}
			else
			{
				motor[RightDrive] = 50;
			}
		}//end first if
	}//end while
}
